// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_anybad
bool rcpp_anybad(IntegerVector indx, int value);
RcppExport SEXP _subsets_rcpp_anybad(SEXP indxSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type indx(indxSEXP);
    Rcpp::traits::input_parameter< int >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_anybad(indx, value));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_sb_str
std::string rcpp_sb_str(std::string x, IntegerVector ind);
RcppExport SEXP _subsets_rcpp_sb_str(SEXP xSEXP, SEXP indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ind(indSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_sb_str(x, ind));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_sb_str_rp
std::string rcpp_sb_str_rp(std::string x, IntegerVector ind, std::string rp_x, IntegerVector rp_ind);
RcppExport SEXP _subsets_rcpp_sb_str_rp(SEXP xSEXP, SEXP indSEXP, SEXP rp_xSEXP, SEXP rp_indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ind(indSEXP);
    Rcpp::traits::input_parameter< std::string >::type rp_x(rp_xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rp_ind(rp_indSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_sb_str_rp(x, ind, rp_x, rp_ind));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_seq_rec
NumericVector rcpp_seq_rec(NumericVector inits, int w, int n, Function f);
RcppExport SEXP _subsets_rcpp_seq_rec(SEXP initsSEXP, SEXP wSEXP, SEXP nSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_seq_rec(inits, w, n, f));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_subsets_rcpp_anybad", (DL_FUNC) &_subsets_rcpp_anybad, 2},
    {"_subsets_rcpp_sb_str", (DL_FUNC) &_subsets_rcpp_sb_str, 2},
    {"_subsets_rcpp_sb_str_rp", (DL_FUNC) &_subsets_rcpp_sb_str_rp, 4},
    {"_subsets_rcpp_seq_rec", (DL_FUNC) &_subsets_rcpp_seq_rec, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_subsets(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
