# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
.anygreater <- function(indx, value) {
    .Call(`_subsets_anygreater`, indx, value)
}

#' @keywords internal
#' @noRd
.anynegative <- function(indx) {
    .Call(`_subsets_anynegative`, indx)
}

#' @export
rcpp_hello_world <- function() {
    .Call(`_subsets_rcpp_hello_world`)
}

#' @keywords internal
#' @noRd
.rcpp_sb_str <- function(x, ind) {
    .Call(`_subsets_rcpp_sb_str`, x, ind)
}

#' @keywords internal
#' @noRd
.rcpp_seq_rec <- function(inits, w, n, f) {
    .Call(`_subsets_rcpp_seq_rec`, inits, w, n, f)
}

